### ISSUE TITLE
Design Inbox page !

### ISSUE THREAD

**Issue by PraveenMalethia** [PraveenMalethia/mumble-vue#27]
Need to create some UI for Inbox!

![image](https://user-images.githubusercontent.com/59171685/119999061-f8aad900-bfee-11eb-86e5-0a515f2ff2e3.png)

similar to this!

**Comment by ghost** [comment]
@PraveenMalethia I think I can work on this. It might take some time but I will try. Can you assign this to me?

**Comment by PraveenMalethia** [comment]
@srikarkandula Assigned!
