### ISSUE TITLE
Follow button not responding immediately

### ISSUE THREAD

**Issue by ghost** [PraveenMalethia/mumble-vue#29]
### Preflight Checklist

* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

#

### Describe the bug

When you click the follow button is does not show the following immediately we have to refresh the page to see the change.
#

### To Reproduce

1. Go to 'usermini.vue'
2. When we click the follow button and after we get the response just add this code ' this.follwing = !this.follwing'

#

### Expected behavior

After we click the follow button we should see an immediate change of the text to follow to following or vice versa.
#

### Add additional instructions and considerations for the assignee

- [ ] Jupiter

- [ ] Saturn

- [ ] Neptune

#

### Screenshots

#

### Additional context

Add any other context about the problem here (include commit numbers and branches if relevant)

**Comment by ghost** [comment]
@PraveenMalethia should I do this or will you just add that code?

**Comment by PraveenMalethia** [comment]
This is because the State is not yet initialized! 
if you can do the vuex thing! then sure you can do it! @srikarkandula

**Comment by ghost** [comment]
Oh ok, actually I dont know anything related about vuex state. Sorry!

**Comment by PraveenMalethia** [comment]
its okay ! we will figure out !
