### ISSUE TITLE
Adding the color to votes that have been made by the user

### ISSUE THREAD

**Issue by ghost** [PraveenMalethia/mumble-vue#32]
### Is your feature request related to a problem? Please describe.

So basically we want the post that is upvoted by the user, that post upvote should be green and the ones that are downvoted should be red.
#

### Describe the solution you'd like

If the user upvoted the mumble then the upvote icon color should be green and if downvoted then downvote icon red or else gray.

#

### Describe alternatives you've considered

Filtering the voters and checking if the current user is a part of them then adding the appropriate color.

#

### Add additional instructions and considerations for the assignee

- [ ] Jupiter

- [ ] Saturn

- [ ] Neptune

#  

### Additional context

Add any other context such as screenshots, schematics, about the feature request here.

**Comment by ghost** [comment]
@PraveenMalethia can you assign this to me

**Comment by PraveenMalethia** [comment]
assigned ! @srikarkandula
