### ISSUE TITLE
Creating Contributor's Page

### ISSUE THREAD

**Issue by ghost** [PraveenMalethia/mumble-vue#34]
### Is your feature request related to a problem? Please describe.

Making the contributors page
#

### Describe the solution you'd like

#

### Describe alternatives you've considered

#

### Add additional instructions and considerations for the assignee

- [ ] Jupiter

- [ ] Saturn

- [ ] Neptune

#  

### Additional context

Add any other context such as screenshots, schematics, about the feature request here.

**Comment by ghost** [comment]
@PraveenMalethia can I work on this?

**Comment by PraveenMalethia** [comment]
@srikarkandula Sure why not !

**Comment by ghost** [comment]
Thank you
