### ISSUE TITLE
Adding 'dark:border-transparent' on all components with border

### ISSUE THREAD

**Issue by ghost** [PraveenMalethia/mumble-vue#36]
### Is your feature request related to a problem? Please describe.

Remove border for darkmode by adding 'dark:border-transparent'
#

### Describe the solution you'd like

Border should not be visible on darkmode.
#

### Describe alternatives you've considered

#

### Add additional instructions and considerations for the assignee

- [ ] Jupiter

- [ ] Saturn

- [ ] Neptune

#  

### Additional context

Add any other context such as screenshots, schematics, about the feature request here.

**Comment by ghost** [comment]
@PraveenMalethia Can you assign this issue to me?

**Comment by PraveenMalethia** [comment]
Assigned

**Comment by ghost** [comment]
Thanks
