### ISSUE TITLE
Adding Remumbled Title

### ISSUE THREAD

**Issue by PraveenMalethia** [PraveenMalethia/mumble-vue#39]
![image](https://user-images.githubusercontent.com/59171685/120889361-49878680-c61a-11eb-83db-da93ced20f19.png)

**Comment by ghost** [comment]
@PraveenMalethia how do we get the user who remumbled username?

**Comment by PraveenMalethia** [comment]
`mumble.original_mumble ? mumble.original_mumble.user.username : mumble.user.username`

By using this !

**Comment by ghost** [comment]
Ok thx can I work on this?

**Comment by PraveenMalethia** [comment]
sure !

**Comment by PraveenMalethia** [comment]
assigned !

**Comment by ghost** [comment]
Thanks

**Comment by ghost** [comment]
@PraveenMalethia this 'mumble.original_mumble ? mumble.original_mumble.user.username : mumble.user.username' is giving me author not user who remumbled.

**Comment by PraveenMalethia** [comment]
you can use any name for now! I will add the dynamic author name!

**Comment by ghost** [comment]
Ok cool
