### ISSUE TITLE
Fixing responsiveness for a mumble.

### ISSUE THREAD

**Issue by ghost** [PraveenMalethia/mumble-vue#44]
When the screen size reduces to a phone the mumble title and time get jumbled and the options dots goes out of place.
So, we need to reduce the font size of content, time and the author of the mumble when the screen size becomes small and add a 'truncate class' so if the name is too big it will be naaammm... .

**Comment by ghost** [comment]
@PraveenMalethia can you assign this issue to me?

**Comment by ghost** [comment]
Also will such a issue come under a bug?

**Comment by PraveenMalethia** [comment]
you can count this type of issue in enhancement !

**Comment by ghost** [comment]
Ok thx

**Comment by ghost** [comment]
@PraveenMalethia why have you closed this issue? Has it been fixed?
