### ISSUE TITLE
SideNavBar on small screens fix

### ISSUE THREAD

**Issue by ghost** [PraveenMalethia/mumble-vue#49]
### Is your feature request related to a problem? Please describe.

So in medium and small screens when we open the sidenavbar over the screen when we click on a page's link then I want the side navbar to close.
#

### Describe the solution you'd like

Once clicked on the route of a page the side navbar will take you there but also close automatically.
#

### Describe alternatives you've considered

On click emit the function to the parent component where the 'open:true or false' is located and change that.
#

### Add additional instructions and considerations for the assignee

- [ ] Jupiter

- [ ] Saturn

- [ ] Neptune

#  

### Additional context

Add any other context such as screenshots, schematics, about the feature request here.

**Comment by ghost** [comment]
@PraveenMalethia can you assign this issue to me?

**Comment by PraveenMalethia** [comment]
done  @srikarkandula
