### ISSUE TITLE
adding timestamp ui to notification panel 

### ISSUE THREAD

**Issue by PraveenMalethia** [PraveenMalethia/mumble-vue#51]
![image](https://user-images.githubusercontent.com/59171685/121804664-2afe3c80-cc65-11eb-8940-7a802297c9d0.png)

like a week ago , a mint ago etc

**Comment by ghost** [comment]
Can you assign this issue to me @PraveenMalethia?

**Comment by PraveenMalethia** [comment]
done @srikarkandula
