### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by codyseibert** [PraveenMalethia/mumble-vue#6]
create a basic login page which hits the mumble API's `api/user/login` endpoint and stores the returned access token, refresh token, and user into vuex state, and put them into local storage for the application to fetch when loaded

**Comment by codyseibert** [comment]
<img width="1669" alt="Screen Shot 2021-05-25 at 1 14 21 AM" src="https://user-images.githubusercontent.com/1868782/119442828-8a1c0180-bcf6-11eb-86e2-52f752ffc60e.png">

It looks like this page exists, it just needs to be hooked up with functionality

**Comment by PraveenMalethia** [comment]
yes page exists just need to hook up !

**Comment by PraveenMalethia** [comment]
can you do vuex setup for auth or will you use nuxt auth module for state management for user ??
